name: one_second_diary
description: Record one second of your day, everyday.

publish_to: 'none'

version: 1.1.3+6

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  get: 
  camera:
    git:
      url: https://github.com/KyleKun/plugins.git
      path: packages/camera/camera/
  flutter_colorpicker:
  path_provider:
  shared_preferences: 
  flutter_ffmpeg: 
  permission_handler:
  tapioca:
    git:
      url: https://github.com/KyleKun/tapioca.git
      ref: master
  salomon_bottom_bar:
  introduction_screen:
  avatar_glow:
  url_launcher:
  rive:
  native_device_orientation:
  video_player:
  about:
  share:
  open_file:
  group_radio_button:
  flutter_local_notifications: 
  timezone:
  timer_builder:
  # logger:
  # device_preview:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - CHANGELOG.md
    - CONTRIBUTORS.md
    - TODO.md
    - TODO_pt.md

  fonts:
    - family: Magic
      fonts:
        - asset: assets/fonts/YuseiMagic-Regular.ttf
