name: one_second_diary
description: Record one second of your day, everyday.

publish_to: 'none'

version: 1.1.3+7

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  about: null
  avatar_glow: null
  camera:
    git:
      url: https://github.com/KyleKun/plugins.git
      path: packages/camera/camera/
  flutter:
    sdk: flutter
  flutter_colorpicker: null
  flutter_ffmpeg: null
  flutter_local_notifications: null
  fluttertoast: ^8.1.1
  get: null
  group_radio_button: null
  introduction_screen: null
  native_device_orientation: null
  open_file: null
  path_provider: null
  permission_handler: null
  rive: null
  salomon_bottom_bar: null
  share: null
  shared_preferences: null
  tapioca:
    git:
      url: https://github.com/daoxve/tapioca.git
      ref: android-dependency-patch
  timer_builder: null
  timezone: null
  url_launcher: null
  video_player: null
#logger:
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - CHANGELOG.md
    - CONTRIBUTORS.md
    - TODO.md
    - TODO_pt.md

  fonts:
    - family: Magic
      fonts:
        - asset: assets/fonts/YuseiMagic-Regular.ttf
